#ifndef FILEANALYZER_H
#define FILEANALYZER_H

#include <QString>
#include <QStringList>

// ── FileCopyItem ────────────────────────────────────────────────────────
// One entry in a FileCopyPlan. Mirrors WPF FileCopyItem.
// Holds everything FileCopier needs to execute the copy.
struct FileCopyItem
{
    enum ItemType {
        File,
        Directory
    };

    QString sourcePath;       // absolute path on disk
    QString destPath;         // absolute path on disk
    QString relativePath;     // relative to plan's source root, e.g. "src/foo/bar.txt"
    ItemType itemType = File;
    qint64 sizeBytes = 0;    // for files: file size. For directories: 0 (sizes aggregated separately)

    bool isOverwrite() const
    {
        // Caller may pre-check whether destPath already exists; this is just a hint.
        return false;
    }
};

// ── FileCopyPlan ────────────────────────────────────────────────────────
// Snapshot of what to copy. Generated by FileAnalyzer before any disk writes.
// Mirrors WPF FileCopyPlan.
struct FileCopyPlan
{
    QString sourceRoot;         // directory the user dropped/pasted
    QString destRoot;           // where everything is going
    QList<FileCopyItem> items;  // flat list, dirs before their children
    qint64 totalBytes = 0;
    bool isSameLocation = false;  // true if sourceRoot == destRoot (caller may abort)

    // Path below is for the rel-path between source and dest.
    // (Kept simple — Qt's QDir does the relative path math in analyzer.)
    static QString formatBytes(qint64 bytes)
    {
        if (bytes < 0) return QString();
        if (bytes < 1024) return QString::number(bytes) + " B";
        if (bytes < 1024 * 1024) return QString::number(bytes / 1024.0, 'f', 1) + " KB";
        if (bytes < 1024 * 1024 * 1024) return QString::number(bytes / (1024.0 * 1024), 'f', 1) + " MB";
        return QString::number(bytes / (1024.0 * 1024 * 1024), 'f', 1) + " GB";
    }
};

// ── FileAnalyzer (static helpers) ───────────────────────────────────────
// Two-phase design (matches WPF FileAnalyzer):
//   Phase 1: Analyze() builds a plan snapshot (no disk writes)
//   Phase 2: FileCopier executes the plan
//
// Static functions — no state, deterministic, testable.
class FileAnalyzer
{
public:
    // Build a plan from a list of source paths, all going to destRoot.
    // - One source path may be a file or directory
    // - Multiple paths allowed
    // - Skips .svn directories
    // - Computes relativePath, totalBytes, isSameLocation
    //
    // Returns empty plan if any source is invalid.
    static FileCopyPlan analyze(const QStringList &sources, const QString &destRoot);

    // Overload: single source
    static FileCopyPlan analyzeOne(const QString &source, const QString &destRoot);
};

#endif // FILEANALYZER_H
